export const fondos = [
  { label: 'Unicornios 1', value: './images/uni_1.png' },
  { label: 'Unicornios 2', value: './images/uni_2.png' },
  { label: 'Unicornios 3', value: './images/uni_3.png' },
  { label: 'Unicornios 4', value: './images/uni_4.png' },
  { label: 'Unicornios 5', value: './images/uni_5.png' },
  // { label: 'Autos 1', value: './images/autos_cumple_1.png' },
  // { label: 'Autos 2', value: './images/autos_cumple_2.png' },
  // { label: 'Dinosaurios 1', value: './images/dinosaurios_cumple_1.png' },
  // { label: 'Dinosaurios 2', value: './images/dinosaurios_cumple_2.png' },
  // { label: 'Dinosaurios 3', value: './images/dinosaurios_cumple_3.png' },
  // { label: 'Fiesta 1', value: './images/fiesta_cumple_1.png' },
  // { label: 'Fiesta 2', value: './images/fiesta_cumple_2.png' },
  // { label: 'Fiesta 3', value: './images/fiesta_cumple_3.png' },
  // { label: 'Hadas 1', value: './images/hadas_cumple_1.png' },
  // { label: 'Hadas 2', value: './images/hadas_cumple_2.png' },
  // { label: 'Hadas 3', value: './images/hadas_cumple_3.png' },
  // { label: 'Hadas 4', value: './images/hadas_cumple_4.png' },
  // { label: 'Robots 1', value: './images/robots_cumple_1.png' },
  // { label: 'Robots 2', value: './images/robots_cumple_2.png' },
]
