export const fondos = [
  { label: 'Hoja en Blanco', value: '/images/blank.png' },
  { label: 'Abstract 01', value: '/images/abstract_01.webp' },
  { label: 'Abstract 02', value: '/images/abstract_02.webp' },
  { label: 'Abstract 03', value: '/images/abstract_03.webp' },
  { label: 'Abstract 04', value: '/images/abstract_04.webp' },
  {
    label: 'Abstract Geometric 01',
    value: '/images/abstract_geometric_01.webp',
  },
  {
    label: 'Abstract Geometric 02',
    value: '/images/abstract_geometric_02.webp',
  },
  {
    label: 'Abstract Geometric 02 Mov',
    value: '/videos/abstract_geometric_02_mov.mp4',
  },
  {
    label: 'Abstract Geometric 03',
    value: '/images/abstract_geometric_03.webp',
  },
  {
    label: 'Abstract Geometric 04',
    value: '/images/abstract_geometric_04.webp',
  },
  { label: 'Alien Pixel 01', value: '/images/alien_pixel_01.webp' },
  { label: 'Alien Pixel 02', value: '/images/alien_pixel_02.webp' },
  { label: 'Alien Pixel 03', value: '/images/alien_pixel_03.webp' },
  { label: 'Alien Pixel 04', value: '/images/alien_pixel_04.webp' },
  { label: 'Argentina Futbol 01', value: '/images/argentina_futbol_01.webp' },
  { label: 'Argentina Futbol 02', value: '/images/argentina_futbol_02.webp' },
  {
    label: 'Argentina Futbol 02 Mov',
    value: '/videos/argentina_futbol_marco_mov.mp4',
  },
  { label: 'Argentina Futbol 03', value: '/images/argentina_futbol_03.webp' },
  { label: 'Art 01', value: '/images/art_01.webp' },
  { label: 'Art 02', value: '/images/art_02.webp' },
  { label: 'Art 03', value: '/images/art_03.webp' },
  { label: 'Art 04', value: '/images/art_04.webp' },
  { label: 'Autos 01', value: '/images/autos_01.webp' },
  { label: 'Autos 02', value: '/images/autos_02.png' },
  { label: 'Autos 03', value: '/images/autos_03.png' },
  { label: 'Dinosaurios 01', value: '/images/dinosaurios_01.png' },
  { label: 'Dinosaurios 02', value: '/images/dinosaurios_02.png' },
  { label: 'Dinosaurios 03', value: '/images/dinosaurios_03.png' },
  { label: 'Dinosaurios 04', value: '/images/dinosaurios_04.png' },
  { label: 'Dinosaurios 05', value: '/images/dinosaurios_05.png' },
  { label: 'Dinosaurios 06', value: '/images/dinosaurios_06.png' },
  { label: 'Espacio 01', value: '/images/espacio_01.png' },
  { label: 'Espacio 02', value: '/images/espacio_02.png' },
  { label: 'Espacio 03', value: '/images/espacio_03.png' },
  { label: 'Espacio 04', value: '/images/espacio_04.png' },
  { label: 'Espacio Pixel 01', value: '/images/espacio_pixel_01.png' },
  { label: 'Espacio Pixel 02', value: '/images/espacio_pixel_02.png' },
  { label: 'Espacio Pixel 03', value: '/images/espacio_pixel_03.png' },
  { label: 'Espacio Pixel 04', value: '/images/espacio_pixel_04.png' },
  { label: 'Flores 01', value: '/images/flores_01.png' },
  { label: 'Flores 02', value: '/images/flores_02.png' },
  { label: 'Flores 03', value: '/images/flores_03.png' },
  { label: 'Flores 04', value: '/images/flores_04.png' },
  { label: 'Granja 01', value: '/images/granja_01.png' },
  { label: 'Granja 02', value: '/images/granja_02.png' },
  { label: 'Granja 03', value: '/images/granja_03.png' },
  { label: 'Granja 04', value: '/images/granja_04.png' },
  { label: 'Granja Noche 01', value: '/images/granja_noche_01.png' },
  { label: 'Granja Noche 02', value: '/images/granja_noche_02.png' },
  { label: 'Granja Noche 03', value: '/images/granja_noche_03.png' },
  { label: 'Granja Noche 04', value: '/images/granja_noche_04.png' },
  { label: 'Hadas 01', value: '/images/hadas_01.jpg' },
  { label: 'Hadas 01 Mov', value: '/videos/hadas_marco_01_mov.mp4' },
  { label: 'Hadas 02', value: '/images/hadas_02.jpg' },
  { label: 'Hadas 03', value: '/images/hadas_03.jpg' },
  { label: 'Hadas 04', value: '/images/hadas_04.jpg' },
  { label: 'Halloween 01', value: '/images/halloween_01.png' },
  { label: 'Halloween 02', value: '/images/halloween_02.png' },
  { label: 'Halloween 03', value: '/images/halloween_03.png' },
  { label: 'Halloween 04', value: '/images/halloween_04.png' },
  { label: 'Maze 01', value: '/images/maze_01.png' },
  { label: 'Maze 02', value: '/images/maze_02.png' },
  { label: 'Maze 03', value: '/images/maze_03.png' },
  { label: 'Maze 04', value: '/images/maze_04.png' },
  { label: 'Maze 05', value: '/images/maze_05.png' },
  { label: 'Maze 06', value: '/images/maze_06.png' },
  { label: 'Maze 07', value: '/images/maze_07.png' },
  { label: 'Maze 08', value: '/images/maze_08.png' },
  { label: 'Mundo Marino 01', value: '/images/mundo_marino_01.png' },
  { label: 'Mundo Marino 02', value: '/images/mundo_marino_02.png' },
  { label: 'Mundo Marino 03', value: '/images/mundo_marino_03.png' },
  { label: 'Mundo Marino 04', value: '/images/mundo_marino_04.png' },
  { label: 'Naturaleza 01', value: '/images/naturaleza_01.png' },
  { label: 'Naturaleza 02', value: '/images/naturaleza_02.png' },
  { label: 'Naturaleza 03', value: '/images/naturaleza_03.png' },
  { label: 'Naturaleza 04', value: '/images/naturaleza_04.png' },
  { label: 'Osos 01', value: '/images/osos_01.png' },
  { label: 'Osos 02', value: '/images/osos_02.png' },
  { label: 'Osos 03', value: '/images/osos_03.png' },
  { label: 'Osos 04', value: '/images/osos_04.png' },
  { label: 'Parques 01', value: '/images/parques_01.png' },
  { label: 'Parques 02', value: '/images/parques_02.png' },
  { label: 'Parques 03', value: '/images/parques_03.png' },
  { label: 'Parques 04', value: '/images/parques_04.png' },
  { label: 'Pixel Art 01', value: '/images/pixel_art_01.png' },
  { label: 'Pixel Art 02', value: '/images/pixel_art_02.png' },
  { label: 'Pixel Art 02 Mov', value: '/videos/pixel_art_02_mov.mp4' },
  { label: 'Psico 01', value: '/images/psico_01.png' },
  { label: 'Psico 02', value: '/images/psico_02.png' },
  { label: 'Psico 03', value: '/images/psico_03.png' },
  { label: 'Psico 04', value: '/images/psico_04.png' },
  { label: 'Robots 01', value: '/images/robots_01.png' },
  { label: 'Robots 02', value: '/images/robots_02.png' },
  { label: 'Robots 03', value: '/images/robots_03.png' },
  { label: 'Robots 04', value: '/images/robots_04.png' },
  { label: 'Teatro 01', value: '/images/teatro_01.png' },
  {
    label: 'Teatro 01 Mov',
    value: '/videos/teatro_01_mov.mp4',
  },
  { label: 'Teatro 02', value: '/images/teatro_02.png' },
  { label: 'Teatro 03', value: '/images/teatro_03.png' },
  { label: 'Teatro 04', value: '/images/teatro_04.png' },
  { label: 'Trenes 01', value: '/images/trenes_01.png' },
  { label: 'Trenes 02', value: '/images/trenes_02.png' },
  { label: 'Trenes 03', value: '/images/trenes_03.png' },
  { label: 'Trenes 04', value: '/images/trenes_04.png' },
  { label: 'Unicornios 01', value: '/images/unicornios_01.png' },
  { label: 'Unicornios 02', value: '/images/unicornios_02.png' },
  { label: 'Unicornios 03', value: '/images/unicornios_03.png' },
  { label: 'Unicornios 04', value: '/images/unicornios_04.png' },
  { label: 'Unicornios 05', value: '/images/unicornios_05.png' },
]
