export const fondos = [
  { label: 'Argentina Futbol 01', value: './images/argentina_futbol_01.png' },
  { label: 'Argentina Futbol 02', value: './images/argentina_futbol_02.png' },
  {
    label: 'Argentina Futbol 02 Mov',
    value: './videos/argentina_futbol_marco_mov.mp4',
  },
  { label: 'Argentina Futbol 03', value: './images/argentina_futbol_03.png' },
  { label: 'Dinosaurios 01', value: './images/dinosaurios_01.png' },
  { label: 'Dinosaurios 02', value: './images/dinosaurios_02.png' },
  {
    label: 'Dinosaurios 02 Mov',
    value: './videos/dinosaurios_bebes_marco_mov.mp4',
  },
  { label: 'Dinosaurios 03', value: './images/dinosaurios_03.png' },
  { label: 'Dinosaurios 04', value: './images/dinosaurios_04.png' },
  { label: 'Espacio 01', value: './images/espacio_01.png' },
  { label: 'Espacio 02', value: './images/espacio_02.png' },
  { label: 'Espacio 03', value: './images/espacio_03.png' },
  { label: 'Espacio 04', value: './images/espacio_04.png' },
  { label: 'Hadas 01', value: './images/hadas_01.jpg' },
  { label: 'Hadas 02', value: './images/hadas_02.jpg' },
  { label: 'Hadas 03', value: './images/hadas_03.jpg' },
  { label: 'Hadas 04', value: './images/hadas_04.jpg' },
  { label: 'Mundo Marino 01', value: './images/mundo_marino_01.png' },
  { label: 'Mundo Marino 02', value: './images/mundo_marino_02.png' },
  { label: 'Mundo Marino 03', value: './images/mundo_marino_03.png' },
  { label: 'Mundo Marino 04', value: './images/mundo_marino_04.png' },
  { label: 'Unicornios 01', value: './images/unicornios_01.png' },
  { label: 'Unicornios 02', value: './images/unicornios_02.png' },
  { label: 'Unicornios 03', value: './images/unicornios_03.png' },
  { label: 'Unicornios 04', value: './images/unicornios_04.png' },
  { label: 'Unicornios 05', value: './images/unicornios_05.png' },
]
